# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pr:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: 'UseDotNet@2'
  displayName: 'Use .NET Core 3.1.x'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
   command: 'restore'
#   arguments: '--configuration $(buildConfiguration)'
   projects: 'ObsDynamicOverlay.sln'
- task: DotNetCoreCLI@2
  displayName: 'Build .NET Core'
  inputs:
   command: 'build'
#   arguments: '--configuration $(buildConfiguration)'
   projects: 'ObsDynamicOverlay.sln'
- task: Npm@1
  displayName: 'Install NPM packages'
  inputs:
    command: 'install'
    workingDir: 'ObsDynamicOverlay.Web'
- task: Npm@1
  displayName: 'Compile TypeScript'
  inputs:
    command: 'custom'
    workingDir: 'ObsDynamicOverlay.Web'
    customCommand: 'run release'
